language: node_js
node_js:
  - "node"
branches:
  only:
    - master
    - develop
sudo: required
script:
  - npm run pretest
  - npm run lint
  - npm run test:coveralls
env:
  global:
    - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
